### ISSUE TITLE
Handling Timeout errors

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [cisco-ce/pyxows#2]
When a device is not accessible or the IP address got miswritten, the connection will end up not being established with a TimeoutError, such as:
`TimeoutError: [Errno 10060] Connect call failed ('192.168.1.3', 443)`

This Timeout error is wrapped into an aiohttp exception:
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.3:443 ssl:False [Connect call failed ('192.168.1.3', 443)]

Resulting in an stacktrace error, and the following console logs:
- Unclosed client session
- client_session: <aiohttp.client.ClientSession object at 0x037CF1D0>

**Comment by ObjectIsAdvantag** [comment]
I'd suggest to manage the exception at:
https://github.com/cisco-ce/pyxows/blob/master/xows/__init__.py#L119

**Comment by xim** [comment]
Thanks. These now raise `ConnectionError`.
