### ISSUE TITLE
installing pyxows gives out error

### ISSUE THREAD

**Issue by matid-lab** [cisco-ce/pyxows#3]
Hi,

tried installing the file  pyxows by using below command

c:\Users\INTRIVEDIM\pyxows>python setup.py install [--user]
invalid command name '[--user]'
[error.txt](https://github.com/cisco-ce/pyxows/files/4430931/error.txt)

**Comment by xim** [comment]
The `[--user]` part of the syntax indicates that it's an optional argument. Try running

    python setup.py install --user
