### ISSUE TITLE
multiple instances of the same argument

### ISSUE THREAD

**Issue by hwdevops** [cisco-ce/pyxows#7]
Does pyxows support a command with multiple instances of the same argument, e.g.

Command:
```
xCommand Presentation Start Layout: Equal ConnectorId: 2 ConnectorId: 3 SendingMode: LocalRemote
```

Request:
```
{
"jsonrpc": "2.0",
"id": 115,
"method": "xCommand/Presentation/Start",
    "params": {
         "Layout": "Equal",
         "ConnectorId": [2, 3],
         "SendingMode": "LocalRemote"
    }
}
```

Or another example is:

```
xCommand Call Join CallId: 2 CallId: 3
```

**Comment by xim** [comment]
Sorry for the late response. It does. Or, the library does. I suspect the command line tool might not. I'll have to consider fixing that if anyone's using it...
