### ISSUE TITLE
Support for Multi-line commands?

### ISSUE THREAD

**Issue by DJF3** [cisco-ce/pyxows#9]
Team,

Does the library support **_multiline commands_**?
Example: 
- [UserInterface Extensions Panel Save](https://roomos.cisco.com/xapi/Command.UserInterface.Extensions.Panel.Save)
- [Macros Macro Save](https://roomos.cisco.com/xapi/Command.Macros.Macro.Save)

These have, besides "arguments", a "body" field for more data. Example from the doc links above:

POST `https://webexapis.com/v1/xapi/command/UserInterface.Extensions.Panel.Save`:

`
{
  "deviceId": "Y2lzY29zcGFya.....S9mb29iYXIv",
  "arguments": {
    "PanelId": "value"
  },
  "body": "Raw data here..."
};
`

**Comment by xim** [comment]
Yes. You can pass the parameter as `body` in this library as well.

On the command line you can do the same:

`clixows -u username -p password endpoint.example.com command Macros Macro Save Name=foo body=`

**Comment by DJF3** [comment]
Would that be something like this?

```
print('COMMAND:', await client.xCommand(['Macros', 'Macro', 'Save'], Name="My Test Macro", 
 Overwrite="True", Body="import xapi from 'xapi';\n console.log('does this work?');"))
```

**Comment by xim** [comment]
Lower case b in body, and I think you're home free
